# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@pluxbox.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import radiomanager_sdk
from radiomanager.program_api import ProgramApi  # noqa: E501
from radiomanager_sdk.rest import ApiException


class TestProgramApi(unittest.TestCase):
    """ProgramApi unit test stubs"""

    def setUp(self):
        self.api = radiomanager.program_api.ProgramApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_program(self):
        """Test case for create_program

        Create program.  # noqa: E501
        """
        pass

    def test_delete_program_by_id(self):
        """Test case for delete_program_by_id

        Delete program by id  # noqa: E501
        """
        pass

    def test_get_program_by_id(self):
        """Test case for get_program_by_id

        Get program by id  # noqa: E501
        """
        pass

    def test_list_programs(self):
        """Test case for list_programs

        Get all programs.  # noqa: E501
        """
        pass

    def test_update_program_by_id(self):
        """Test case for update_program_by_id

        Update program by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
