# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@pluxbox.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import radiomanager_sdk
from radiomanager_sdk.models.program_relations_broadcasts import ProgramRelationsBroadcasts  # noqa: E501
from radiomanager_sdk.rest import ApiException


class TestProgramRelationsBroadcasts(unittest.TestCase):
    """ProgramRelationsBroadcasts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProgramRelationsBroadcasts(self):
        """Test ProgramRelationsBroadcasts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = radiomanager_sdk.models.program_relations_broadcasts.ProgramRelationsBroadcasts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
