# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: support@pluxbox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import radiomanager_sdk
from radiomanager_sdk.models.story_input_only import StoryInputOnly  # noqa: E501
from radiomanager_sdk.rest import ApiException


class TestStoryInputOnly(unittest.TestCase):
    """StoryInputOnly unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStoryInputOnly(self):
        """Test StoryInputOnly"""
        # FIXME: construct object with mandatory attributes with example values
        # model = radiomanager_sdk.models.story_input_only.StoryInputOnly()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
