# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@pluxbox.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import radiomanager_sdk
from radiomanager.contact_api import ContactApi  # noqa: E501
from radiomanager_sdk.rest import ApiException


class TestContactApi(unittest.TestCase):
    """ContactApi unit test stubs"""

    def setUp(self):
        self.api = radiomanager.contact_api.ContactApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_contact(self):
        """Test case for create_contact

        Create contact.  # noqa: E501
        """
        pass

    def test_delete_contact_by_id(self):
        """Test case for delete_contact_by_id

        Delete contact by id  # noqa: E501
        """
        pass

    def test_get_contact_by_id(self):
        """Test case for get_contact_by_id

        Get contact by id  # noqa: E501
        """
        pass

    def test_list_contacts(self):
        """Test case for list_contacts

        Get all contacts.  # noqa: E501
        """
        pass

    def test_update_contact_by_id(self):
        """Test case for update_contact_by_id

        Update contact by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
