# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@pluxbox.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import radiomanager_sdk
from radiomanager_sdk.models.inline_object3 import InlineObject3  # noqa: E501
from radiomanager_sdk.rest import ApiException


class TestInlineObject3(unittest.TestCase):
    """InlineObject3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject3(self):
        """Test InlineObject3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = radiomanager_sdk.models.inline_object3.InlineObject3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
