# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@pluxbox.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import radiomanager_sdk
from radiomanager_sdk.models.model_type_output_only import ModelTypeOutputOnly  # noqa: E501
from radiomanager_sdk.rest import ApiException


class TestModelTypeOutputOnly(unittest.TestCase):
    """ModelTypeOutputOnly unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelTypeOutputOnly(self):
        """Test ModelTypeOutputOnly"""
        # FIXME: construct object with mandatory attributes with example values
        # model = radiomanager_sdk.models.model_type_output_only.ModelTypeOutputOnly()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
