# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@pluxbox.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import radiomanager_sdk
from radiomanager_sdk.models.item_relations_contacts_params import ItemRelationsContactsParams  # noqa: E501
from radiomanager_sdk.rest import ApiException


class TestItemRelationsContactsParams(unittest.TestCase):
    """ItemRelationsContactsParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemRelationsContactsParams(self):
        """Test ItemRelationsContactsParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = radiomanager_sdk.models.item_relations_contacts_params.ItemRelationsContactsParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
