# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@pluxbox.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import radiomanager_sdk
from radiomanager_sdk.models.not_found import NotFound  # noqa: E501
from radiomanager_sdk.rest import ApiException


class TestNotFound(unittest.TestCase):
    """NotFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotFound(self):
        """Test NotFound"""
        # FIXME: construct object with mandatory attributes with example values
        # model = radiomanager_sdk.models.not_found.NotFound()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
