# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: support@pluxbox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import radiomanager_sdk
from radiomanager_sdk.models.unprocessable_entity import UnprocessableEntity  # noqa: E501
from radiomanager_sdk.rest import ApiException


class TestUnprocessableEntity(unittest.TestCase):
    """UnprocessableEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnprocessableEntity(self):
        """Test UnprocessableEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = radiomanager_sdk.models.unprocessable_entity.UnprocessableEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
