# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: support@pluxbox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import radiomanager_sdk
from radiomanager_sdk.models.import_item import ImportItem  # noqa: E501
from radiomanager_sdk.rest import ApiException


class TestImportItem(unittest.TestCase):
    """ImportItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImportItem(self):
        """Test ImportItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = radiomanager_sdk.models.import_item.ImportItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
