# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: support@pluxbox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import radiomanager_sdk
from radiomanager_sdk.models.contact_data_input import ContactDataInput  # noqa: E501
from radiomanager_sdk.rest import ApiException


class TestContactDataInput(unittest.TestCase):
    """ContactDataInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContactDataInput(self):
        """Test ContactDataInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = radiomanager_sdk.models.contact_data_input.ContactDataInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
