# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: support@pluxbox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import radiomanager_sdk
from radiomanager_sdk.api.station_api import StationApi  # noqa: E501
from radiomanager_sdk.rest import ApiException


class TestStationApi(unittest.TestCase):
    """StationApi unit test stubs"""

    def setUp(self):
        self.api = radiomanager_sdk.api.station_api.StationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_station(self):
        """Test case for get_station

        Get own station only  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
