# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@pluxbox.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import radiomanager_sdk
from radiomanager.genre_api import GenreApi  # noqa: E501
from radiomanager_sdk.rest import ApiException


class TestGenreApi(unittest.TestCase):
    """GenreApi unit test stubs"""

    def setUp(self):
        self.api = radiomanager.genre_api.GenreApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_genre_by_id(self):
        """Test case for get_genre_by_id

        Get genre by id  # noqa: E501
        """
        pass

    def test_list_genres(self):
        """Test case for list_genres

        List all genres.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
