# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@pluxbox.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "Pluxbox RadioManager Client"
VERSION = "1.1.13"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="RadioManager",
    author="Pluxbox",
    author_email="support@pluxbox.com",
    url="http://pluxbox.com",
    keywords=["OpenAPI", "OpenAPI-Generator", "RadioManager"],
    install_requires=REQUIRES,
    license='MIT',
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="License",
    long_description="""\
    RadioManager  # noqa: E501
    """
)
