# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@pluxbox.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from radiomanager_sdk.configuration import Configuration


class InlineObject2(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'start': 'datetime',
        'allow_playlist_past': 'int',
        'before_id': 'int',
        'previous_id': 'int',
        'items': 'list[ImportItem]'
    }

    attribute_map = {
        'start': 'start',
        'allow_playlist_past': 'allow_playlist_past',
        'before_id': 'before_id',
        'previous_id': 'previous_id',
        'items': 'items'
    }

    def __init__(self, start=None, allow_playlist_past=None, before_id=None, previous_id=None, items=None, local_vars_configuration=None):  # noqa: E501
        """InlineObject2 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._start = None
        self._allow_playlist_past = None
        self._before_id = None
        self._previous_id = None
        self._items = None
        self.discriminator = None

        if start is not None:
            self.start = start
        if allow_playlist_past is not None:
            self.allow_playlist_past = allow_playlist_past
        if before_id is not None:
            self.before_id = before_id
        if previous_id is not None:
            self.previous_id = previous_id
        if items is not None:
            self.items = items

    @property
    def start(self):
        """Gets the start of this InlineObject2.  # noqa: E501


        :return: The start of this InlineObject2.  # noqa: E501
        :rtype: datetime
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this InlineObject2.


        :param start: The start of this InlineObject2.  # noqa: E501
        :type: datetime
        """

        self._start = start

    @property
    def allow_playlist_past(self):
        """Gets the allow_playlist_past of this InlineObject2.  # noqa: E501


        :return: The allow_playlist_past of this InlineObject2.  # noqa: E501
        :rtype: int
        """
        return self._allow_playlist_past

    @allow_playlist_past.setter
    def allow_playlist_past(self, allow_playlist_past):
        """Sets the allow_playlist_past of this InlineObject2.


        :param allow_playlist_past: The allow_playlist_past of this InlineObject2.  # noqa: E501
        :type: int
        """

        self._allow_playlist_past = allow_playlist_past

    @property
    def before_id(self):
        """Gets the before_id of this InlineObject2.  # noqa: E501


        :return: The before_id of this InlineObject2.  # noqa: E501
        :rtype: int
        """
        return self._before_id

    @before_id.setter
    def before_id(self, before_id):
        """Sets the before_id of this InlineObject2.


        :param before_id: The before_id of this InlineObject2.  # noqa: E501
        :type: int
        """

        self._before_id = before_id

    @property
    def previous_id(self):
        """Gets the previous_id of this InlineObject2.  # noqa: E501


        :return: The previous_id of this InlineObject2.  # noqa: E501
        :rtype: int
        """
        return self._previous_id

    @previous_id.setter
    def previous_id(self, previous_id):
        """Sets the previous_id of this InlineObject2.


        :param previous_id: The previous_id of this InlineObject2.  # noqa: E501
        :type: int
        """

        self._previous_id = previous_id

    @property
    def items(self):
        """Gets the items of this InlineObject2.  # noqa: E501


        :return: The items of this InlineObject2.  # noqa: E501
        :rtype: list[ImportItem]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this InlineObject2.


        :param items: The items of this InlineObject2.  # noqa: E501
        :type: list[ImportItem]
        """

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineObject2):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineObject2):
            return True

        return self.to_dict() != other.to_dict()
