# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@pluxbox.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from radiomanager_sdk.configuration import Configuration


class ModelTypeOptions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'color': 'str',
        'sub_broadcast': 'bool'
    }

    attribute_map = {
        'color': 'color',
        'sub_broadcast': 'subBroadcast'
    }

    def __init__(self, color=None, sub_broadcast=None, local_vars_configuration=None):  # noqa: E501
        """ModelTypeOptions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._color = None
        self._sub_broadcast = None
        self.discriminator = None

        if color is not None:
            self.color = color
        if sub_broadcast is not None:
            self.sub_broadcast = sub_broadcast

    @property
    def color(self):
        """Gets the color of this ModelTypeOptions.  # noqa: E501


        :return: The color of this ModelTypeOptions.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this ModelTypeOptions.


        :param color: The color of this ModelTypeOptions.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def sub_broadcast(self):
        """Gets the sub_broadcast of this ModelTypeOptions.  # noqa: E501


        :return: The sub_broadcast of this ModelTypeOptions.  # noqa: E501
        :rtype: bool
        """
        return self._sub_broadcast

    @sub_broadcast.setter
    def sub_broadcast(self, sub_broadcast):
        """Sets the sub_broadcast of this ModelTypeOptions.


        :param sub_broadcast: The sub_broadcast of this ModelTypeOptions.  # noqa: E501
        :type: bool
        """

        self._sub_broadcast = sub_broadcast

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelTypeOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ModelTypeOptions):
            return True

        return self.to_dict() != other.to_dict()
