# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: support@pluxbox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from radiomanager_sdk.models.broadcast_relations_model_type import BroadcastRelationsModelType  # noqa: F401,E501
from radiomanager_sdk.models.presenter_relations_broadcasts import PresenterRelationsBroadcasts  # noqa: F401,E501
from radiomanager_sdk.models.presenter_relations_programs import PresenterRelationsPrograms  # noqa: F401,E501


class PresenterRelations(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'programs': 'PresenterRelationsPrograms',
        'broadcasts': 'PresenterRelationsBroadcasts',
        'model_type': 'BroadcastRelationsModelType'
    }

    attribute_map = {
        'programs': 'programs',
        'broadcasts': 'broadcasts',
        'model_type': 'model_type'
    }

    def __init__(self, programs=None, broadcasts=None, model_type=None):  # noqa: E501
        """PresenterRelations - a model defined in Swagger"""  # noqa: E501

        self._programs = None
        self._broadcasts = None
        self._model_type = None
        self.discriminator = None

        if programs is not None:
            self.programs = programs
        if broadcasts is not None:
            self.broadcasts = broadcasts
        if model_type is not None:
            self.model_type = model_type

    @property
    def programs(self):
        """Gets the programs of this PresenterRelations.  # noqa: E501


        :return: The programs of this PresenterRelations.  # noqa: E501
        :rtype: PresenterRelationsPrograms
        """
        return self._programs

    @programs.setter
    def programs(self, programs):
        """Sets the programs of this PresenterRelations.


        :param programs: The programs of this PresenterRelations.  # noqa: E501
        :type: PresenterRelationsPrograms
        """

        self._programs = programs

    @property
    def broadcasts(self):
        """Gets the broadcasts of this PresenterRelations.  # noqa: E501


        :return: The broadcasts of this PresenterRelations.  # noqa: E501
        :rtype: PresenterRelationsBroadcasts
        """
        return self._broadcasts

    @broadcasts.setter
    def broadcasts(self, broadcasts):
        """Sets the broadcasts of this PresenterRelations.


        :param broadcasts: The broadcasts of this PresenterRelations.  # noqa: E501
        :type: PresenterRelationsBroadcasts
        """

        self._broadcasts = broadcasts

    @property
    def model_type(self):
        """Gets the model_type of this PresenterRelations.  # noqa: E501


        :return: The model_type of this PresenterRelations.  # noqa: E501
        :rtype: BroadcastRelationsModelType
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type):
        """Sets the model_type of this PresenterRelations.


        :param model_type: The model_type of this PresenterRelations.  # noqa: E501
        :type: BroadcastRelationsModelType
        """

        self._model_type = model_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PresenterRelations):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
