# coding: utf-8

"""
    RadioManager

    RadioManager  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@pluxbox.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from radiomanager_sdk.configuration import Configuration


class TagRelations(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'broadcasts': 'TagRelationsBroadcasts',
        'programs': 'TagRelationsPrograms',
        'contacts': 'TagRelationsContacts',
        'items': 'TagRelationsItems'
    }

    attribute_map = {
        'broadcasts': 'broadcasts',
        'programs': 'programs',
        'contacts': 'contacts',
        'items': 'items'
    }

    def __init__(self, broadcasts=None, programs=None, contacts=None, items=None, local_vars_configuration=None):  # noqa: E501
        """TagRelations - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._broadcasts = None
        self._programs = None
        self._contacts = None
        self._items = None
        self.discriminator = None

        if broadcasts is not None:
            self.broadcasts = broadcasts
        if programs is not None:
            self.programs = programs
        if contacts is not None:
            self.contacts = contacts
        if items is not None:
            self.items = items

    @property
    def broadcasts(self):
        """Gets the broadcasts of this TagRelations.  # noqa: E501


        :return: The broadcasts of this TagRelations.  # noqa: E501
        :rtype: TagRelationsBroadcasts
        """
        return self._broadcasts

    @broadcasts.setter
    def broadcasts(self, broadcasts):
        """Sets the broadcasts of this TagRelations.


        :param broadcasts: The broadcasts of this TagRelations.  # noqa: E501
        :type: TagRelationsBroadcasts
        """

        self._broadcasts = broadcasts

    @property
    def programs(self):
        """Gets the programs of this TagRelations.  # noqa: E501


        :return: The programs of this TagRelations.  # noqa: E501
        :rtype: TagRelationsPrograms
        """
        return self._programs

    @programs.setter
    def programs(self, programs):
        """Sets the programs of this TagRelations.


        :param programs: The programs of this TagRelations.  # noqa: E501
        :type: TagRelationsPrograms
        """

        self._programs = programs

    @property
    def contacts(self):
        """Gets the contacts of this TagRelations.  # noqa: E501


        :return: The contacts of this TagRelations.  # noqa: E501
        :rtype: TagRelationsContacts
        """
        return self._contacts

    @contacts.setter
    def contacts(self, contacts):
        """Sets the contacts of this TagRelations.


        :param contacts: The contacts of this TagRelations.  # noqa: E501
        :type: TagRelationsContacts
        """

        self._contacts = contacts

    @property
    def items(self):
        """Gets the items of this TagRelations.  # noqa: E501


        :return: The items of this TagRelations.  # noqa: E501
        :rtype: TagRelationsItems
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this TagRelations.


        :param items: The items of this TagRelations.  # noqa: E501
        :type: TagRelationsItems
        """

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TagRelations):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TagRelations):
            return True

        return self.to_dict() != other.to_dict()
